### ISSUE TITLE
Question about the plot function

### ISSUE THREAD

**Issue by Pierre9344** [cellmapslab/longmixr#13]
Hi,

When I use the plot function on the cluster_model object, there are at least 8 plots that are generated at once. I use rmarkdown to generate report and I find that all to have all those plots next to each other is a bit heavy. Moreover, I only use the concensus matrix and the consensus CDF plots.
May I ask you if it would be possible to add individual functions forthe different plots or parameters in the actual function to select which plots need to be printed.

**Comment by jonas-hag** [comment]
That's a very good suggestion. I have added the parameter `which_plots` to `plot.lcc` so that you can specify which plots you want. Please have a look at the detailed documentation in `plot.lcc`.

To use this feature, you need to install the latest version from github, as it is not on CRAN yet:

```
remotes::install_github("cellmapslab/longmixr")
```

Please let me know if it works as intended.

**Comment by Pierre9344** [comment]
Hello,

Sorry for the late answer. The function does exactly what I wanted.
